
service: user-service

provider:
 name: aws
 runtime: python3.9
 region: us-east-1
 memorySize: 128
 stage: ${opt:stage, "dev"}

package:
  individually: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: common-layer
      description: Common requirements Layer


functions:
  app:
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
     - http: ANY /
     - http: 'ANY {proxy+}'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    package:
      include:
        - "main.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".venv/**"
        - "node_modules/**"
